ORIGINALS = '/home/nayara/ARTIGO-PS/CROPPED_ORIGINAL_IMAGES/'

GRAYSCALE = '/home/nayara/ARTIGO-PS/CROPPED_GRAY_IMAGES/'

REDSCALE = '/home/nayara/ARTIGO-PS/CROPPED_RED_IMAGES/'

GREENSCALE = '/home/nayara/ARTIGO-PS/CROPPED_GREEN_IMAGES/'

BLUESCALE = '/home/nayara/ARTIGO-PS/CROPPED_BLUE_IMAGES/'

RESULTS = '/home/nayara/ARTIGO-PS/RESULTS/'

RESULTS_GRAY = '/GRAYSCALE/'

RESULTS_RED = '/REDSCALE/'

RESULTS_GREEN = '/GREENSCALE/'

RESULTS_BLUE = '/BLUESCALE/'
